floorist: add separate blueprint floorist query (HMS-4496)
osbuild/image-builder-crc pull request #1288
Opened 2024-08-01 14:28 UTC by avitova

2024-08-02 09:07 UTC, ezr-ondrej requested changes, later dismissed

2024-08-02 09:07 UTC, ezr-ondrej commented on templates/image-builder.yml
> -          v.blueprint_id::text as blueprint_id,
hmm :thinking:
I'm thinking this is still pretty useful info, I'd probably keep both blueprint_id and version, so you can connect the dots.
"What blueprint and version this compose was build from" :)

It feels to me that we want to have both :)

2024-08-06 13:42 UTC, avitova commented
Alright! So, I kept all the info we have for builds, including the version_id, blueprint_id, and a deleted_at. Even deleted_at might help us know more if we see that the blueprint was never built and was deleted.
So this just adds a new query now, and is rebased.

2024-08-06 18:25 UTC, lzap commented on templates/image-builder.yml
> +          v.blueprint_id::text as blueprint_id, v.version, b.deleted
```suggestion
          v.blueprint_id::text as blueprint_id, v.version, b.deleted,
```

I haven’t tried the query but I would expect a comma here?

2024-08-06 21:47 UTC, ezr-ondrej reviewed
What Lukas said +1 more nit, but looks good to me apart of that :)

(Just an anecdote: blueprint_versions join blueprints breaks my brain for some reason, I'd always do it the other way around for some reason)

2024-08-06 21:47 UTC, ezr-ondrej commented on templates/image-builder.yml
> +          b.metadata->>'parent_id' as parent_id,
```suggestion
          b.metadata->>'parent_id' as parent_id
```

2024-08-07 08:59 UTC, avitova commented
Of course, you are right, guys. I tested the query now, and this now would really work.

2024-08-07 09:12 UTC, ezr-ondrej approved these changes
Nice! :+1:

2024-08-07 09:31 UTC, lzap approved these changes

2024-08-07 09:32 UTC, lzap commented
Schulz is red

2024-08-07 09:53 UTC, avitova commented
Let's try after rebase:)

2024-08-07 11:01 UTC, avitova commented
Meh, this failed again, even though I do not think the failure is related. :thinking:

2024-08-07 11:02 UTC, ezr-ondrej commented
Yeah probably unrelated, let me click the retry button and lets see :)

2024-08-07 17:35 UTC, merged

2024-08-07 17:35 UTC, ezr-ondrej commented
Nice! Thanks! :orange_heart: