internal/v1: add BlueprintV1 nested body
osbuild/image-builder-crc pull request #965
Opened 2023-12-21 13:26 UTC by avitova

This PR adds a wrapper around the body parameters. In this way, we would not have to marshal/unmarshal the name, version and description parameters from/to json.
I came to the conclusion, that the nested struct should be anonymous, it felt cumbersome to have something like BlueprintBodyV1, BlueprintBodyV2 etc. This feels like the best solution.

2023-12-21 13:40 UTC, lzap requested changes
Nice, this is a breaking change but I would no bump the version to 2 in this case, no records are in stage yet and locally we can just delete incompatible blueprints.

2023-12-21 13:41 UTC, lzap commented
After this PR is merged, you may need to delete existing blueprints because they will contain "empty body" since that field will not be present. @amirfefer @ezr-ondrej

2023-12-21 13:51 UTC, avitova commented on internal/v1/handler_blueprints.go
> +	} `json:"blueprint_body"`
Not really:)

2024-01-02 08:31 UTC, avitova commented
Rebased:)

2024-01-02 12:42 UTC, lzap commented
Ondra brought a great observation: name, description and version is already stored in the DB in separate fields. We should consider the opposite approach - removing version, name and description from the type (and JSON) completely, we can copy these from DB fields into the result. @ezr-ondrej ?

2024-01-02 13:08 UTC, lzap requested changes
Because blueprint version and body version is misleading, why don't we simplify 

```
type BlueprintBody struct {
	Customizations Customizations `json:"customizations"`
	Distribution   Distributions  `json:"distribution"`
	ImageRequests  []ImageRequest `json:"image_requests"`
}
```

2024-01-02 14:46 UTC, ezr-ondrej commented
Yup, that sounds like exactly what I had in mind :+1:

@avitova let us know if that makes sense to you. Honestly I'd be fine if we keep your approach and just created the `BlueprintBody` struct as named typed if you'd prefer.
I just do not see too much value in the `BlueprintV1` struct in this case.

2024-01-02 15:51 UTC, lzap commented
Thanks, we had a call and agreed that simplification is the best thing in this case. Let’s do it.

2024-01-03 16:48 UTC, avitova commented
Yeah, we agreed on dropping the version part of the structure name (BlueprintV1), as well as the fields name, description and version. This makes more sense.

2024-01-04 09:06 UTC, ezr-ondrej approved these changes, later dismissed
This is exactly what I imagined :orange_heart:
Thank you!

2024-01-04 12:03 UTC, lzap submitted a review, later dismissed
Thank you, this is much better. Sorry for the weird type introduced :-D

2024-01-04 17:28 UTC, lzap commented
Resolved conflicts. Please squash on merge.

2024-01-11 08:19 UTC, avitova commented
Rebased. It looks like the test is failing due to insufficient coverage. I do not think that this refactoring is the reason for that. :thinking:

2024-01-11 11:02 UTC, ezr-ondrej commented
The test is just hard to read, but the failure is:
```
=== RUN   TestHandlers_ComposeBlueprint
    handler_blueprints_test.go:40: 
        	Error Trace:	/home/runner/work/image-builder/image-builder/internal/v1/handler_blueprints_test.go:40
        	Error:      	Received unexpected error:
        	            	command /usr/bin/podman [exec image_builder_test_1704960418 psql -U postgres -c CREATE DATABASE test1bf32acff1e14dde9e6974f90b405d17;] error: exit status 2, output: psql: error: could not connect to server: No such file or directory
        	            		Is the server running locally and accepting
        	            		connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
        	Test:       	TestHandlers_ComposeBlueprint
--- FAIL: TestHandlers_ComposeBlueprint (0.13s)
```

2024-01-11 11:07 UTC, ezr-ondrej commented
And re-run succeeded :)

2024-01-12 11:28 UTC, avitova commented
Rebased :heavy_check_mark:

2024-01-15 09:11 UTC, croissanne approved these changes
ty!

2024-01-15 09:11 UTC, merged